= Funções Matemáticas
Doc Writer <doc@example.com>
:reproducible: :listing-caption: Listing
:source-highlighter: rouge
:toc:
// Uncomment next line to add a title page (or set doctype to book)
//:title-page:
// Uncomment next line to set page size (default is A4)
//:pdf-page-size: Letter

// An example of a basic http://asciidoc.org[AsciiDoc] document prepared by {author}.

== count
Retornar o total de elementos que satisfazem uma condição
[source,js]
----
var source = Rx.Observable.range(0, 10).count();
var subscription = source.subscribe((value) => console.log(value));
----
No exemplo acima ele irá imprimir a quantidade de elementos.
[source,js]
----
var source = Rx.Observable.range(0, 10).count((x) => x % 2 === 0);
var subscription = source.subscribe((value) => console.log(value));
----
No exemplo acima passamos uma condição para a função “count()”. Ela irá nos retornar o total de itens pares.

== max
Retorna o maior valor.
[source,js]
----
var sourceMAX = Rx.Observable.from([1, 3, 5, 7, 9, 2, 4, 6, 8]).max();

var subscriptionMAX = source.subscribe((value) => console.log(value));
----

== min
Retorna o menor valor
[source,js]
----

var sourceMIN = Rx.Observable.from([1, 3, 5, 7, 9, 2, 4, 6, 8]).min();

var subscriptionMIN = source.subscribe((value) => console.log(value));
----

== reduce
Faz uma redução, acumulando os valores em um único lugar.
[source,js]
----
var sourceReducer = Rx.Observable.from([1, 2, 3, 4, 5]).reduce(
  (total, current) => total + current
);

var subscriptionReducer = source.subscribe((value) => console.log(value));
----

A função “reduce()” está recebendo uma variável que segura o total e outra que receberá cada elemento do array. Nós retornamos uma soma, então no final teremos a soma de todos os elementos