= Hot N Cold
Doc Writer <doc@example.com>
:reproducible: :listing-caption: Listing
:source-highlighter: rouge
:toc:
// Uncomment next line to add a title page (or set doctype to book)
//:title-page:
// Uncomment next line to set page size (default is A4)
//:pdf-page-size: Letter

An example of a basic http://asciidoc.org[AsciiDoc] document prepared by {author}.

== Cold Observables
Os Observables do tipo Cold são os que a gente já viu: a função que envia valores só começa a ser executada quando alguém se inscreve, e os valores não são compartilhados. Cada inscrito receberá um valor.
[source,js]
----
var source = Rx.Observable.interval(1000);

var subscription = source.subscribe(
    value => console.log(`My Value is ${value}`)
)
----
Indicamos que queremos um intervalo de 1 segundo (1000 milisegundos) com a função “interval()”. Depois, nos inscrevemos para poder imprimir cada um dos valores enviados.

Se criarmos uma nova inscrição, os valores serão diferentes.

== Hot Observables
Já os Observables do tipo Hot são diferentes. Vamos ver um exemplo:

[source,js]
----
var source = Rx.Observable.interval(1000);
var hot = source.publish();

var subscription = hot.subscribe(
    value => console.log(`My Value is ${value}`)
)
----

Fizemos o mesmo código do Observable do tipo Cold, com a diferença que utilizamos a função “publish()” para transformar nosso Observable em um tipo Hot.

Veja que apenas ter feito a inscrição não foi o suficiente para os valores começarem a serem enviados. Para que isso ocorra precisamos executar o comando:

[source,js]
----
hot.connect();
----

[range]
* Hot Observables seriam como assistir um vídeo do YouTube ao vivo: não importa a hora em que você se conectar. Todos que estão assistindo estarão vendo a mesma coisa que você sendo transmitida;
* Cold Observables seriam como selecionar um vídeo no YouTube que esteja gravado: cada um no mundo que iniciar o vídeo começará vendo desde o “0:00”. Uma pessoa pode estar assistindo já no momento “3:17”, mas quem começou a assistir agora estará ainda no “0:05”, ou seja, cada um está recebendo algo diferente.
