= Observables - Funções de Lista
Doc Writer <doc@example.com>
:reproducible: :listing-caption: Listing
:source-highlighter: rouge
:toc:
// Uncomment next line to add a title page (or set doctype to book)
//:title-page:
// Uncomment next line to set page size (default is A4)
//:pdf-page-size: Letter

// An example of a basic http://asciidoc.org[AsciiDoc] document prepared by {author}.

== map
O map serve para pegarmos cada um dos elementos de uma lista e transformar em uma outra estrutura.
[source,js]
----
var items = [{ a: 1 }, { a: 2 }, { a: 3 }, { a: 4 }];

var sourceMaps = Rx.Observable.from(items);
var subscriptionMaps = sourceMaps
  .map((x) => {
    return { value: x.a };
  })
  .subscribe((x) => console.log(x));
----
No exemplo acima, utilizamos a função “map()” para alterar a estrutura da entrada original. Isso é muito útil para quando estamos fazendo uma integração, e a entrada ou saída dos dois pontos participantes são diferentes.

== filter
Como o próprio nome diz, estamos realizando um filtro.
[source,js]
----
var sourceFilter = Rx.Observable.from([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
var subscriptionFilter = sourceFilter
  .filter((x) => x % 2 === 0)
  .subscribe((x) => console.log(x));
----
No exemplo acima deixamos apenas os números pares prosseguirem.

== take
Retornar apenas um determinado número de elementos
[source,js]
----
var sourceTake = Rx.Observable.from([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
var subscriptionTake = sourceTake.take(3).subscribe((x) => console.log(x));
----

== find
Faz uma busca nos elementos e retorna o primeiro que bater com a condição passada.
[source,js]
----
var sourceFind = Rx.Observable.from(people);
var subscriptionFind = sourceFind
  .find((x) => x.age > 18)
  .subscribe((x) => console.log(x));
----
No exemplo acima temos uma lista de pessoas com nome e idade. Passamos uma busca em que a condição é alguém com idade maior que 18. O primeiro elemento que bater com a condição passada será retornado.

== first
Retorna o primeiro elemento que satisfaça a condição.
[source,js]
----
var peopleFirst = [
  { name: "Rick", age: 10 },
  { name: "Rose", age: 25 },
  { name: "Cassandra", age: 13 },
  { name: "Henry", age: 22 },
];

var sourceFirst = Rx.Observable.from(people);
var subscriptionFirst = sourceFirst
  .first((x) => x.name[0] === "R")
  .subscribe((x) => console.log(x));
----
Aqui nós retornamos a primeira pessoa em que seu nome comece com a letra “R”.

== last
Retorna o último elemento que satisfaça a condição.
[source,js]
----
var peopleLast = [
  { name: "Rick", age: 10 },
  { name: "Rose", age: 25 },
  { name: "Cassandra", age: 13 },
  { name: "Henry", age: 22 },
];

var sourceLast = Rx.Observable.from(people);
var subscriptionLast = sourceLast
  .last((x) => x.name[0] === "R")
  .subscribe((x) => console.log(x));
----
Aqui nós retornamos a última pessoa em que seu nome comece com a letra “R”.

== pluck
Passamos o nome de um dos campos do elemento. Esse campo será arrancado da lista original e será a raiz do novo elemento.
[source,js]
----
var peoplePluck = [
  { name: "Rick", age: 10 },
  { name: "Rose", age: 25 },
  { name: "Cassandra", age: 13 },
  { name: "Henry", age: 22 },
];

var sourcePluck = Rx.Observable.from(peoplePluck);
var subscriptionPluck = sourcePluck
  .pluck("name")
  .subscribe((x) => console.log(x));
----
No exemplo acima, arrancamos o campo “name”, e como resultado, temos agora uma lista apenas de nomes.